# tensorflow学习

## 验证安装成功

In [7]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf
print(tf.__version__)

2.0.0


## 张量定义

In [8]:
c0 = tf.constant(2, name='c0') # 0阶张量
c1 = tf.constant([1, 2, 3], name='c1') # 1阶张量
c2 = tf.constant([[1,2],[3,4]], name='c2') # 2阶张量

In [10]:
print(c0)
print(c1)
print(c2)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## 张量的数学运算

In [15]:
a = tf.constant([[1,2],[3,4]],name='a')
b = tf.constant([[5,6],[7,8]],name='b')
# 加法
tf.add(a,b,name='add')

<tf.Tensor: id=19, shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>

In [16]:
# 减法
tf.subtract(a,b,name='sub')

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]], dtype=int32)>

In [17]:
# 对应元素相乘
tf.multiply(a,b,name='multiply')

<tf.Tensor: id=21, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [18]:
# 对应矩阵相乘
tf.matmul(a,b,name='matmul')

<tf.Tensor: id=22, shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>