# pytorch

## 先安装pytorch
请在官网复制命令，并切换到你的py环境运行：
```
conda activate /Users/fy/opt/anaconda3/envs/jupyterlab
conda install pytorch torchvision torchaudio -c pytorch
```
## 验证pytorch安装成功

In [5]:
import torch
import torchvision
print(torch.__version__)

1.12.1


## 张量
### 张量创建

In [11]:
x = torch.randn(3, 2, 1)
print(x)

tensor([[[ 0.7685],
         [-0.5485]],

        [[ 0.4496],
         [ 0.1704]],

        [[ 0.9912],
         [-0.4395]]])


### 根据py列表创建张量

In [13]:
x = torch.tensor([[2,3],[4,5]])
print(x)

tensor([[2, 3],
        [4, 5]])


### 创建全零张量

In [17]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


### 基于现有张量创建新的张量

In [22]:
x = torch.zeros(2, 2)
y = torch.ones_like(x)
print(x)
print(y)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


### 指定数据类型

In [25]:
x = torch.ones(2, 2, dtype=torch.int)
print(x)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


### 张量的数学运算

In [35]:
x = torch.ones(2,2)
print(x)
y = torch.ones(2,2)
# z = x + y
z = torch.add(x,y)
print(z)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])


### 张量的值相乘 

In [38]:
x = torch.tensor([[1,2],[2,3]])
y = torch.tensor([[1,2],[2,3]])
x.mul(y)

tensor([[1, 4],
        [4, 9]])

### 矩阵相乘

In [41]:
x.mm(y)

tensor([[ 5,  8],
        [ 8, 13]])

### 张量转换为numpy数组

In [42]:
a = torch.ones(2,2)
b = a.numpy()
print(type(a))
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [49]:
a = a + 2
print(a)
print(b)

tensor([[14., 14.],
        [14., 14.]])
[[1. 1.]
 [1. 1.]]


### numpy数组转换为张量

In [52]:
import numpy as np
import torch
a = np.array([[1,1],[1,1]])
b = torch.from_numpy(a)
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [53]:
np.add(a,1,out=a)

array([[2, 2],
       [2, 2]])

In [54]:
print(b)

tensor([[2, 2],
        [2, 2]])


### CUDA 张量

In [59]:
a = torch.ones(2,2)
if torch.cuda.is_available():
    a_cuda = a.cuda()
    print(a_cuda)
else:
    print('gpu not exits')

gpu not exits


## 自动求导

### 深度学习的本质是通过反向传播求导数！！！

In [66]:
x = torch.ones(2,2,requires_grad = True)
print(x.requires_grad)
y = torch.ones(2,2,requires_grad = True)
print(y.requires_grad)

True
True


### 返回值是标量

In [67]:
z = x + y
z = z.mean()
print(z)

tensor(2., grad_fn=<MeanBackward0>)


In [68]:
z.backward() # 反向传播

In [69]:
print(x.grad)
print(y.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


### 返回值是张量

In [70]:
z = (2 * x) + (3 * y)

In [71]:
z.backward(torch.ones_like(z)) # 如果z不是一个标量，则需要传入一个大小相同的张量

In [72]:
print(x.grad)
print(y.grad)

tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])
tensor([[3.2500, 3.2500],
        [3.2500, 3.2500]])


## torch.nn 搭建模型

In [75]:
import torch
import torch.nn as nn

In [76]:
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        self.fc = nn.Linear(1, 1)
        # 其他层
    
    def forward(self, x):
        out = self.fc(x)
        return out

In [78]:
net = net_name()
print(net)

net_name(
  (fc): Linear(in_features=1, out_features=1, bias=True)
)


## torch.optim

In [79]:
import torch.optim as optim

In [83]:
criterion = nn.MSELoss() # 损失函数
output = [2] # oh no
target = [3] # oh no
loss = criterion(output,target)
print(loss)

AttributeError: 'list' object has no attribute 'size'

In [ ]:
optimizer = optim.SGD(net.parameters(), lr = 0.01) # 随机梯度下降算法

In [ ]:
optimizer.zero_grad()     # 梯度清零
output = net(input)
loss = criterion(output, target)　　　
loss.backward()
optimizer.step()          # 完成更新